# Generated by Django 2.2.15 on 2020-09-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0025_new_follow_pages_page_xpath_pagination_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='checker_ref_url',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='checker_type',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='checker_x_path',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='checker_x_path_result',
        ),
        migrations.AlterField(
            model_name='checker',
            name='checker_type',
            field=models.CharField(choices=[('4', '404'), ('X', '404_OR_X_PATH')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='checker',
            name='scraped_obj_attr',
            field=models.ForeignKey(help_text='Attribute of type DETAIL_PAGE_URL, several checkers for same DETAIL_PAGE_URL attribute possible.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.ScrapedObjAttr'),
        ),
        migrations.AlterField(
            model_name='checker',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.Scraper'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='scraped_obj_attr',
            field=models.ForeignKey(blank=True, help_text='Empty for main page, attribute of type DETAIL_PAGE_URL scraped from main page for detail pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.ScrapedObjAttr'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.Scraper'),
        ),
        migrations.AlterField(
            model_name='scrapedobjattr',
            name='obj_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.ScrapedObjClass'),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='pagination_page_replace',
            field=models.TextField(blank=True, help_text="RANGE_FUNCT: uses Python range funct., syntax: [start], stop[, step], FREE_LIST: 'Replace text 1', 'Some other text 2', 'Maybe a number 3', ..."),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='scraped_obj_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.ScrapedObjClass'),
        ),
        migrations.AlterField(
            model_name='scraperelem',
            name='scraped_obj_attr',
            field=models.ForeignKey(help_text='The different attributes to be scraped, exactly one attribute of type BASE necessary.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.ScrapedObjAttr'),
        ),
        migrations.AlterField(
            model_name='scraperelem',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.Scraper'),
        ),
    ]
