# Generated by Django 2.2.15 on 2020-10-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0026_auto_20200919_1101'),
        ('dynamic_scraper', '0026_auto_20201003_1703'),
    ]

    operations = [
    ]
